version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/frontend:/app
      - /frontend/app/node_modules
    environment:
      - NODE_ENV=production
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend